name: Build and Test Example Project

on: [push, pull_request]	

jobs:	
  build:	
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, windows-2019, ubuntu-18.04]
        include: 
        - os: macOS-10.14
          TARGET: macos  
        - os: ubuntu-18.04
          TARGET: linux     
        - os: windows-2019
          TARGET: windows
      fail-fast: false

    steps:
    - name: Install Linux dependencies	
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config libreadline-dev
    # Set up Flutter and add it to the path.
    - name: Clone Flutter repository with stable channel
      uses: actions/checkout@v2
      with:
        repository: 'flutter/flutter'
        ref: '1.17.4'
        path: 'flutter'
        fetch-depth: 0
    - name: Add Flutter to the PATH for Unix
      run: echo "::add-path::/$GITHUB_WORKSPACE/flutter/bin"
      if: runner.os != 'Windows'
    - name: Add Flutter to the PATH for Windows
      run: echo "::add-path::${env:GITHUB_WORKSPACE}\flutter\bin"
      if: runner.os == 'Windows'
    - name: Add Dart to the PATH for Unix
      run: echo "::add-path::/$GITHUB_WORKSPACE/flutter/bin/cache/dart-sdk/bin"
      if: runner.os != 'Windows'
    - name: Add Dart to the PATH for Windows
      run: echo "::add-path::${env:GITHUB_WORKSPACE}\flutter\bin\cache\dart-sdk\bin"
      if: runner.os == 'Windows'
    - name: Run Flutter doctor
      run: flutter doctor -v

    - name: Node and NPM Versions
      run: node -v && npm -v

    - name: Clone Hydro-SDK
      uses: actions/checkout@v2
      with:
        path: 'hydro'

    - name: Get packages for Hydro-SDK JS
      run: npm install
      working-directory: hydro/example-project
    - name: Build hello-world.ts
      run: node node_modules/hydro-sdk/dist/compiler -t hello-world.ts -m hello-world -d assets -p debug
      working-directory: hydro/example-project
    - name: Test hello-world.ts
      run: flutter test
      working-directory: hydro/example-project

