name: Waveform Upgrade
on:
  workflow_dispatch:
    inputs:
      depName:
        description: "Dependency to update"
        required: true

      depVersion:
        description: "Version to update to"
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        include:
          - os: ubuntu-18.04
            TARGET: linux
    steps:
      - name: Install Linux Dependencies
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Clone Hydro-SDK
        uses: actions/checkout@v2
        with:
          path: "hydro"

      - name: Get packages for Hydro-SDK JS
        run: npm install
        working-directory: hydro

      - name: Get packages for Hydro-SDK Dart
        run: flutter pub get
        working-directory: hydro

      - name: Configure Git Identity
        env:
          PUBLISH_EMAIL: ${{secrets.PUBLISH_EMAIL}}
          PUBLISH_USERNAME: ${{secrets.PUBLISH_USERNAME}}
        run: |
          git config --global user.email "$PUBLISH_EMAIL"
          git config --global user.name "$PUBLISH_USERNAME"
        working-directory: hydro

      - name: Waveform Install
        run: |
          flutter pub run waveform:install --name=${{github.event.inputs.depName}} --version=${{github.event.inputs.depVersion}}
        working-directory: hydro

      - name: Commit Changes
        run: |
          git checkout -b bump-${{github.event.inputs.depName}}-${{github.event.inputs.depVersion}}
          git push --set-upstream origin bump-${{github.event.inputs.depName}}-${{github.event.inputs.depVersion}}
          git commit -a -m "Bump ${{github.event.inputs.depName}} to ${{github.event.inputs.depVersion}}"

      - name: Open PR
        run: |
          echo ${{CHGIBB_HYDRO_PAT}} > token.txt
          gh auth login --with-token < token.txt
          gp pr create --title "Bump ${{github.event.inputs.depName}} to ${{github.event.inputs.depVersion}}"
